build-job:
  stage: build
  tags:
    - shell
  script:
    - echo "Running build..."
    - docker compose build

test-job:
  stage: test
  tags:
    - shell
  script:
    - echo "Setting up application"
    - docker compose up -d
    - echo "Running tests..."
    - cd tests/
    - npm install
    - node test.mjs
  allow_failure: true
  after_script:
    - echo "Cleaning up"
    - cd ..
    - docker compose down
    

deploy-job:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Deploying build!"
    - docker compose up -d