build-job:
  stage: build
  tags:
    - shell
  script:
    - echo "Running build..."
    - docker-compose build

test-job:
  stage: test
  tags:
    - shell
  script:
    - echo "Running tests..."
    - sleep 5

deploy-job:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Deploying build!"
    - docker-compose up -d