services:
  service1:
    build: ./service1
    environment:
      PORT: "9501"
      SERVICE_2_URL: "http://service2:9502"
    deploy:
      replicas: 3
    ports:
      - "9501:9501"
    networks:
      - internal
      - loadbalancing
    depends_on:
      - service2
    labels:
      - com.akusuvanto=container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service2:
    build: ./service2
    environment:
      PORT: "9502"
    ports:
    - "9502:9502"
    networks:
      - internal
    labels:
      - com.akusuvanto=container

  nginx:
    build: ./nginx
    ports:
      - "8198:8198"
    networks:
      - loadbalancing
      - public
    depends_on:
      - service1
      - service2
    labels:
      - com.akusuvanto=container
    stop_grace_period: 2s
  
  apigateway:
    build: ./apigateway
    environment:
      PORT: "8197"
    ports:
      - "8197:8197"
    networks:
      - internal
      - public
    depends_on:
      - service1
      - service2
    labels:
      - com.akusuvanto=container

networks:
  internal:
    driver: bridge
    internal: true
  loadbalancing:
    driver: bridge
    internal: true
  public:
    driver: bridge