version: "3"
services:

  service1:
    container_name: service-1-nodejs
    build: ./service1
    ports:
      - 8199:8199
    networks:
      - internal
      - public

  service2:
    container_name: service-2-golang
    build: ./service2
    ports:
      - 8198:8198
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge